"""initial_schema

Revision ID: 806cfc3bfdf2
Revises: 
Create Date: 2026-06-30 20:52:43.995812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '806cfc3bfdf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('ctacte',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('id_tipo_doc',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_tipo_iva',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'provincias', ['idprovincia'], ['id'])
        batch_op.create_foreign_key(None, 'categorias', ['idcategoria'], ['id'])
        batch_op.create_foreign_key(None, 'localidades', ['idlocalidad'], ['id'])

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'planes_sistema', ['idplan_sistema'], ['id'])

    with op.batch_alter_table('control_nc', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Control y registro de las notas de creditos\r\nComprobante origen, combrobante que genera y comprobanta por el que ingresa'
    )

    with op.batch_alter_table('cta_cte_prov', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facturac', ['idfactura'], ['id'])

    with op.batch_alter_table('item_balance', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'detalles_articulos', ['id_detalle'], ['id'])
        batch_op.create_foreign_key(None, 'colores', ['id_color'], ['id'])

    with op.batch_alter_table('item_remito_sucs', schema=None) as batch_op:
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'colores', ['id_color'], ['id'])
        batch_op.create_foreign_key(None, 'detalles_articulos', ['id_detalle'], ['id'])

    with op.batch_alter_table('itemsc', schema=None) as batch_op:
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(0)'))
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(0)'))
        batch_op.create_foreign_key(None, 'colores', ['id_color'], ['id'])
        batch_op.create_foreign_key(None, 'detalles_articulos', ['id_detalle'], ['id'])

    with op.batch_alter_table('itemsp', schema=None) as batch_op:
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'colores', ['id_color'], ['id'])
        batch_op.create_foreign_key(None, 'detalles_articulos', ['id_detalle'], ['id'])

    with op.batch_alter_table('itemsv', schema=None) as batch_op:
        batch_op.alter_column('idoferta',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_foreign_key(None, 'colores', ['id_color'], ['id'])
        batch_op.create_foreign_key(None, 'detalles_articulos', ['id_detalle'], ['id'])

    with op.batch_alter_table('localidades', schema=None) as batch_op:
        batch_op.alter_column('localidad',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'provincias', ['id_provincia'], ['id'])

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.alter_column('idsucursal',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('idusuario',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('hora',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('subtitulo',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('mensaje',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('leido',
               existing_type=mysql.SMALLINT(),
               type_=sa.Boolean(),
               nullable=True)

    with op.batch_alter_table('planes_creditos', schema=None) as batch_op:
        batch_op.alter_column('garantes',
               existing_type=mysql.SMALLINT(),
               nullable=True)

    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.alter_column('provincia',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.alter_column('fac_electronica',
               existing_type=mysql.SMALLINT(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('pos_printer',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('rendiciones_caja', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'puntos_venta', ['idpunto_vta'], ['id'])

    with op.batch_alter_table('tipo_comprobantes', schema=None) as batch_op:
        batch_op.alter_column('discrimina_iva',
               existing_type=mysql.SMALLINT(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_comprobantes', schema=None) as batch_op:
        batch_op.alter_column('discrimina_iva',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('rendiciones_caja', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.alter_column('pos_printer',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('fac_electronica',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.alter_column('provincia',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('planes_creditos', schema=None) as batch_op:
        batch_op.alter_column('garantes',
               existing_type=mysql.SMALLINT(),
               nullable=False)

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.alter_column('leido',
               existing_type=sa.Boolean(),
               type_=mysql.SMALLINT(),
               nullable=False)
        batch_op.alter_column('mensaje',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('subtitulo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('hora',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('idusuario',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('idsucursal',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('localidades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('localidad',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('itemsv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('idoferta',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('itemsp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('itemsc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(0)'))
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(0)'))

    with op.batch_alter_table('item_remito_sucs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_detalle',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id_color',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('item_balance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cta_cte_prov', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('control_nc', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Control y registro de las notas de creditos\r\nComprobante origen, combrobante que genera y comprobanta por el que ingresa',
        existing_comment=None
    )

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_tipo_iva',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_tipo_doc',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('ctacte',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
